language: node_js

node_js:
  - "12.12"

jobs:
  include:
    - stage: "Validate"
      name: "Build"
      script: yarn && yarn build
    - name: "Verify yarn.lock"
      script: yarn && yarn check --integrity
    - name: "Lint code"
      # Need to build before linting or else the @projitect/* modules cannot be found
      script: yarn && yarn build && yarn lint
      # Tests are failing for some stupid build reason. Can't figure it out
      # Issue #117 tracks this
#    - name: "Automated tests"
#      script: yarn && yarn test

notifications:
  email: false
